import Head from "next/head";
import Image from "next/image";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.map((item, key) => (
          <div key={key} style={{ border: "1px black solid" }}>
            <h3>Id: {item.uid}</h3>
            <Image src={item.avatar} alt="avatar" height={150} width={150} />
            <p>
              Name: {item.first_name} {item.last_name}
            </p>
            <p>Username: {item.username}</p>
            <p>Email: {item.email}</p>
            <p>Phone Number: {item.phone_number}</p>
            <p>DOB: {item.date_of_birth}</p>
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://random-data-api.com/api/users/random_user?size=50"
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
