import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

export default function Home({ data }) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Create Next App</h1>
      <main>
        {data.map((item, key) => (
          <div key={key}>
            {/* <h3>Id: {item.uid}</h3> */}
            <Image src={item.avatar} alt="avatar" height={100} width={100} />
            <p>
              Name: {item.first_name} {item.last_name}
            </p>
            <p>Username: {item.username}</p>
            <p>Email: {item.email}</p>
            <p>Phone Number: {item.phone_number}</p>
            <p>DOB: {item.date_of_birth}</p>
          </div>
        ))}
      </main>
    </Container>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://random-data-api.com/api/users/random_user?size=100"
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

const Container = styled.div`
  > h1 {
    text-align: center;
  }
  > main {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    > div {
      box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
      padding: 1pc;
      margin: 1pc;
      width: 250px;
    }
  }
`;
